#!/bin/sh

# add plugin-40 if not exists
xfconf-query -c xfce4-panel -p /plugins/plugin-40 -n -t string -s "whiskermenu"

# copy default configuration if not exists
[ -r "$HOME/.config/xfce4/panel/whiskermenu-40.rc" ] ||  cp /etc/xdg/xdg-aurex/xfce4/panel/whiskermenu-40.rc .config/xfce4/panel/

# get array of plugins and:
# 	- replace 1 with 40
#	- replace 2 with 3 (separator)
#	- add '-s' option to each element ('--set' option)

PLUGINS_ARRAY="$(xfconf-query -c xfce4-panel -p /panels/panel-0/plugin-ids |sed -ne  "/^[[:digit:]]/{/^1$/s%1%40%;/^2$/s%2%3%;s%^%-s %;p}" |tr "\n" " ")"

#replace array
xfconf-query -c xfce4-panel -p /panels/panel-0/plugin-ids $PLUGINS_ARRAY

# restart panel
xfce4-panel -r
