#!/bin/sh

PREREQ=""
DESCRIPTION="Setting up mdm automatic login..."

prereqs()
{
       echo "$PREREQ"
}

case $1 in
# get pre-requisites
prereqs)
       prereqs
       exit 0
       ;;
esac

. /scripts/casper-functions

log_begin_msg "$DESCRIPTION"

if [ -d /root/etc/mdm ]; then
    # Configure MDM autologin
    AutologinParameters="AutomaticLoginEnable=true\n\
AutomaticLogin=$USERNAME\n\
TimedLoginEnable=true\n\
TimedLogin=$USERNAME\n\
TimedLoginDelay=10"
    MDMConfFile=/root/etc/mdm/mdm.conf
    [ ! -r $MDMConfFile ] || touch $MDMConfFile
    # Prevent from updating if parameters already present (persistent usb key)
    if ! `grep -qs 'AutomaticLoginEnable' $MDMConfFile` ; then
        if ! `grep -qs '\[daemon\]' $MDMConfFile` ; then
            echo '[daemon]' >> $MDMConfFile
        fi
        sed -i "s/\[daemon\]/\[daemon\]\n$AutologinParameters/" $MDMConfFile
    fi
    if ! `grep -qs 'MinimalUID' $MDMConfFile` ; then
        if ! `grep -qs '\[greeter\]' $MDMConfFile` ; then
            echo '[greeter]' >> $MDMConfFile
        fi
        sed -i "s/\[greeter\]/\[greeter\]\n$MinimalUID=999/" $MDMConfFile
    fi
fi

log_end_msg
