#!/bin/sh

PREREQ=""
DESCRIPTION="Setting up init..."

prereqs()
{
       echo "$PREREQ"
}

case $1 in
# get pre-requisites
prereqs)
       prereqs
       exit 0
       ;;
esac

. /scripts/casper-functions

log_begin_msg "$DESCRIPTION"


for x in $(cat /proc/cmdline); do
	case $x in
		textonly|automatic-ubiquity|only-ubiquity|noninteractive)
			rm -f /root/etc/rc?.d/[SK]??[gkx]dm
		;;
	esac
done
log_end_msg

exit 0
